drf_light_test/urls.py
from django.contrib import admin
from django.urls import path

from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.DivisionViewSet.as_view(), name='index_view'),
]

core/models.py
from django.db import models

from mptt.models import MPTTModel, TreeForeignKey

class Division(MPTTModel):
    """ Подразделение """

    name = models.CharField(
        max_length=512,
        verbose_name='Название'
    )

    parent = TreeForeignKey(
        'self',
        verbose_name='Родитель',
        related_name='children',
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подразделение'
        verbose_name_plural = 'Подразделения'


class Post(models.Model):
    """ Должность """

    name = models.CharField(
        max_length=512,
        verbose_name='Название'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'должности'


class Employee(models.Model):
    """ Сотрудник """

    name = models.CharField(
        max_length=512,
        verbose_name='ФИО'
    )

    post = models.ForeignKey(
        Post,
        verbose_name='Должность',
        on_delete=models.CASCADE,
        blank=False,
        null=False
    )

    date_of_admission = models.DateField(
        verbose_name='Дата приема на работу'
    )

    salary = models.FloatField(
        verbose_name='Размер заработной платы'
    )

    division = models.ForeignKey(
        Division,
        related_name=u'division_employee',
        verbose_name='Подразделение',
        on_delete=models.CASCADE,
        blank=False,
        null=False
    )


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = u'сотрудники'

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.core.exceptions import PermissionDenied

from rest_framework import viewsets
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.views import APIView
from rest_framework.response import Response

from core.models import Division, Post, Employee
from core.serializers import DivisionSerializer


class DivisionViewSet(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'index.html'
    serializer_class = DivisionSerializer

    def get(self, request):
        queryset = Division.objects.filter(parent=None)
        return Response({
            'divisions': queryset
        })

core/templates/base.html
{% load static %}

{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Подразделения</title>

		<meta name="description" content="{% block meta_description %}{% if ex_ceo_description %}{{ ex_ceo_description }}{% else %}{% endif %}{% endblock %}">

        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
<!--        <script src="https://kit.fontawesome.com/f7396c76a1.js" crossorigin="anonymous"></script>-->


        {% compress css %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

            <link rel="stylesheet" href="{% static 'custom/css/custom.css' %}">
        {% endcompress %}

    </head>
    <body>

    <div class="container-fluid">
      <div class="row">
        <main class="px-md-4 mt-4">
          {% block content %}{% endblock %}
        </main>
      </div>
    </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
		{% compress js %}
            <script src="{% static 'custom/js/custom.js' %}"></script>
        {% endcompress %}

        {% block extra_footer %}
        {% endblock %}
    </body>
</html>

core/templates/children_divisions_list.html
<div class="accordion" id="menu-{{ parent.id }}">
  {% for division in division_list %}
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#division-{{ division.id }}">
          {{ division }}
      </button>
    </h2>

    <div id="division-{{ division.id }}" class="accordion-collapse collapse" data-bs-parent="#menu-{{ parent.id }}">

      <div class="row px-3 pt-3 pb-1">
        {% for employee in division.division_employee.all %}
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ employee.name }}</h5>
              <p class="card-text">{{ employee.post }} c {{ employee.date_of_admission }}</p>
              <p class="card-text">Зарплата - {{ employee.salary }} руб.</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

      <div class="accordion-body">
        {% include 'children_divisions_list.html' with division_list=division.children.all parent=division %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

core/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% load mptt_tags %}
{% block content %}

<div class="accordion" id="menu">
    {% include 'children_divisions_list.html' with division_list=divisions %}
</div>


{% endblock %}